---
label: Global site config
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: snipcart_api_key
  label: Snipcart public API key
- type: text
  name: footer_text
  label: Footer Text
- type: file
  name: logo_light
  label: Logo Light
- type: file
  name: logo_dark
  label: Logo Dark
- type: file
  name: favicon
  label: favicon
- type: file
  name: hamburger_background_image
  label: Hamburger menu background image
- type: file
  name: bg_image_primary
  label: Primary Backround Image
  description: Primary Backround Image (JPG or PNG)
- type: file
  name: bg_image_secondary
  label: Secondary Backround Image
  description: Secondary Backround Image (JPG or PNG)
- type: file
  name: bg_image_product
  label: Product Backround Image
  description: Product Backround Image (JPG or PNG)
- type: select
  name: palette
  label: Color Palette
  config:
    source:
      type: custom
    options:
    - default
- type: field_group
  name: palettes
  label: Palettes
  hidden: true
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
- type: field_group_list
  name: main_menu
  label: Navigation Links
  description: List of navigation links.
  fields:
  - type: include
    name: include_action
    label: Action
    template: action
  config:
    labelField: title
pages:
- site-metadata.json
